config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  resources :post_attachments
  resources :posts do
  	member do
  put "like", to: "posts#upvote"
  put "dislike", to: "posts#downvote"
 end
 resources :comments
end
  root to: "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	has_attached_file :image, styles: {large: "600x600>", medium: "300x300>", thumb: "150x150#"}
	 validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	acts_as_votable
	belongs_to :user
	has_many :comments

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  #build from user id instead from intial post id
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_back fallback_location: root_path
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    redirect_back fallback_location: root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :elevation, :location, :distance, :level, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, html: {multipart: true}) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :elevation %>
    <%= form.text_field :elevation %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :distance %>
    <%= form.text_field :distance %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.text_field :level %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hiking News</h1>
<div class="post">
    <% @posts.each do |post| %>
    <div class="link row clearfix">
        Location: <%= post.location%>
        <%= post.title %>
        Elevation: <%= post.elevation %>
        Distance: <%= post.distance %>
        Level: <%= post.level %>
        <button><%= link_to 'View', post %></button>
        <%= image_tag post.image.url(:medium) %>
        <%if post.user == current_user %>
        <button><%= link_to 'Edit Venture', edit_post_path(post) %></button>
        <button><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></button>
        <% end %>
        
      <small class="author">Posted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %></small>
    
    <div class="btn-group">
      <%= link_to like_post_path(post), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-up"></span>
        Like
        <%= post.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_post_path(post), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-down">
        Dislike
        <%= post.get_downvotes.size %>
      <% end %>
    </div>
    <% end %>
</div>
<br>




  

app/views/posts/new.html.erb
<h1>New Post</h1>
<div class="form-group">
<%= render 'form', post: @post %>
</div>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @post.image.url(:medium) %> 


<p>
  <strong>Elevation:</strong>
  <%= @post.elevation %>
</p>

<p>
  <strong>Location:</strong>
  <%= @post.location %>
</p>

<p>
  <strong>Distance:</strong>
  <%= @post.distance %>
</p>

<p>
  <strong>Level:</strong>
  <%= @post.level %>
</p>
<%if @post.user == current_user %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<button><%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %></button>
<% end %>

<%= link_to 'Back', posts_path %> 
<div class="comment">
<h3 class="comments_title">
  <%= @post.comments.count %> Comments
</h3>

<div id="comments">
  <%= render :partial => @post.comments %>
</div>
<%= simple_form_for [@post, Comment.new]  do |f| %>
  <div class="field">
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <br>
  <%= f.submit "Add Comment", class: "btn btn-primary" %>
</div>
<% end %>